import os
import json
import logging
import asyncio
import signal
import threading
from aiokafka import AIOKafkaConsumer
import httpx
import psycopg2
from psycopg2.extras import Json
from psycopg2 import pool
from prometheus_client import Counter, Histogram, start_http_server

# ═══════════════════════════════════════════════════════════════════════════
# Logging
# ═══════════════════════════════════════════════════════════════════════════
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# ═══════════════════════════════════════════════════════════════════════════
# Prometheus Metrics
# ═══════════════════════════════════════════════════════════════════════════
PROM_PORT = int(os.environ.get('METRICS_PORT', '9090'))

TOKENS_INPUT = Counter(
    'medgemma_input_tokens_total',
    'Total billable input tokens consumed',
    ['consumer']
)
TOKENS_OUTPUT = Counter(
    'medgemma_output_tokens_total',
    'Total output tokens generated by vLLM',
    ['consumer']
)
JOBS_COMPLETED = Counter(
    'medgemma_jobs_completed_total',
    'Total jobs completed successfully',
    ['consumer']
)
JOBS_FAILED = Counter(
    'medgemma_jobs_failed_total',
    'Total jobs that failed',
    ['consumer']
)
JOB_DURATION = Histogram(
    'medgemma_job_duration_seconds',
    'Job processing duration (vLLM inference time)',
    ['consumer'],
    buckets=[1, 5, 10, 30, 60, 120, 300, 600]
)

# ═══════════════════════════════════════════════════════════════════════════
# Environment variables
# ═══════════════════════════════════════════════════════════════════════════
KAFKA_BROKERS = os.environ.get('KAFKA_BROKERS', 'kafka:9092')
KAFKA_TOPIC = os.environ.get('KAFKA_TOPIC', 'llm-jobs')
KAFKA_GROUP_ID = os.environ.get('KAFKA_GROUP_ID', 'llm-jobs-worker-group')

PG_HOST = os.environ.get('PG_HOST', 'kong-database')
PG_PORT = os.environ.get('PG_PORT', '5432')
PG_USER = os.environ.get('PG_USER', 'kong')
PG_PASSWORD = os.environ.get('PG_PASSWORD', 'kong')
PG_DATABASE = os.environ.get('PG_DATABASE', 'kong')

VLLM_URL = os.environ.get('VLLM_URL', 'http://213.173.107.138:20804/v1/chat/completions')
CONCURRENCY_LIMIT = int(os.environ.get('CONCURRENCY_LIMIT', '128'))
VLLM_TIMEOUT = int(os.environ.get('VLLM_TIMEOUT', '120'))

# ═══════════════════════════════════════════════════════════════════════════
# DB connection pool
# ═══════════════════════════════════════════════════════════════════════════
db_pool = None

def init_db_pool():
    global db_pool
    db_pool = pool.ThreadedConnectionPool(
        minconn=10,
        maxconn=150,
        host=PG_HOST,
        port=PG_PORT,
        user=PG_USER,
        password=PG_PASSWORD,
        database=PG_DATABASE
    )
    logger.info("DB connection pool initialized (min=10, max=150).")


def update_job_status(job_id, status, result=None, error=None):
    conn = None
    try:
        conn = db_pool.getconn()
        cur = conn.cursor()
        if result is not None:
            cur.execute(
                "UPDATE llm_jobs SET status = %s, result = %s, updated_at = NOW() WHERE job_id = %s",
                (status, Json(result), job_id)
            )
        elif error is not None:
            cur.execute(
                "UPDATE llm_jobs SET status = %s, error = %s, updated_at = NOW() WHERE job_id = %s",
                (status, error, job_id)
            )
        else:
            cur.execute(
                "UPDATE llm_jobs SET status = %s, updated_at = NOW() WHERE job_id = %s",
                (status, job_id)
            )
        conn.commit()
        cur.close()
    except Exception as e:
        logger.error(f"Failed to update job {job_id} in DB: {e}")
        if conn:
            conn.rollback()
        raise  # Critical: Raise error so process_job fails and offset is not committed
    finally:
        if conn:
            db_pool.putconn(conn)

db_semaphore = None

async def safe_update_job_status(*args, **kwargs):
    async with db_semaphore:
        await asyncio.to_thread(update_job_status, *args, **kwargs)


def calculate_billable_input_tokens(payload):
    """
    Müşteriye faturalanacak input token sayısını hesaplar.

    Tüm bileşenler aynı BPE tahmini ile hesaplanır:
    Her 4 karakter ≈ 2.5 token (len * 25 // 40)
    """
    messages = payload.get("messages", [])
    total_chars = 0

    for msg in messages:
        content = msg.get("content")

        if isinstance(content, str):
            total_chars += len(content)
            continue

        if isinstance(content, list):
            for part in content:
                if part.get("type") == "text":
                    total_chars += len(part.get("text", ""))
                elif part.get("type") == "image_url":
                    url = part.get("image_url", {}).get("url", "")
                    if url.startswith("data:image/"):
                        try:
                            _, b64_data = url.split(",", 1)
                            total_chars += len(b64_data)
                        except ValueError:
                            pass

    return max(1, total_chars * 25 // 40)


def sanitize_image_payload(payload):
    """
    Kafka JSON serialization sırasında base64 verisinde oluşabilecek
    whitespace/newline/escape sorunlarını temizler.
    vLLM'in data URI'yi image token olarak işlemesini garanti eder.
    """
    messages = payload.get("messages")
    if not messages:
        return payload

    for msg in messages:
        content = msg.get("content")
        if not isinstance(content, list):
            continue
        for part in content:
            if part.get("type") != "image_url":
                continue
            image_url_obj = part.get("image_url", {})
            url = image_url_obj.get("url", "")
            if not url.startswith("data:image/"):
                continue

            try:
                header, b64_data = url.split(",", 1)
            except ValueError:
                continue

            b64_clean = b64_data.replace("\n", "").replace("\r", "").replace(" ", "").replace("\t", "")
            image_url_obj["url"] = f"{header},{b64_clean}"
            logger.info(f"Image sanitized: {len(b64_data)} -> {len(b64_clean)} chars")

    return payload


async def process_job(job_id, payload, client, consumer="default"):
    logger.info(f"[job={job_id}] Processing...")
    await safe_update_job_status(job_id, "PROCESSING")

    import time
    start_time = time.time()

    try:
        payload.pop("medasista_metadata", None)

        # Müşteriye faturalanacak input token'ı hesapla (sanitize'dan ÖNCE)
        billable_input_tokens = calculate_billable_input_tokens(payload)

        # Base64 verisini temizle — Kafka JSON round-trip sırasında
        # oluşan whitespace/escape sorunları vLLM'in görüntüyü text
        # token olarak işlemesine neden olur
        payload = sanitize_image_payload(payload)

        response = await client.post(VLLM_URL, json=payload, timeout=float(VLLM_TIMEOUT))

        if response.status_code == 200:
            raw_result = response.json()

            content = ""
            choices = raw_result.get("choices", [])
            if choices and isinstance(choices, list) and choices[0].get("message"):
                content = choices[0]["message"].get("content", "")

            # Output tokens: vLLM'in gerçek üretim sayısı (güvenilir)
            vllm_output_tokens = raw_result.get("usage", {}).get("completion_tokens", 0)

            # Müşteriye gösterilecek usage:
            # - input_tokens: bizim hesapladığımız (system + user text + image BPE)
            # - output_tokens: vLLM'in gerçek completion token sayısı
            # - total_tokens: input + output toplamı
            total_tokens = billable_input_tokens + vllm_output_tokens

            simplified_result = {
                "content": content,
                "usage": {
                    "input_tokens": billable_input_tokens,
                    "output_tokens": vllm_output_tokens,
                    "total_tokens": total_tokens
                }
            }

            logger.info(f"[job={job_id}] Completed. Input(billable): {billable_input_tokens}, Output: {vllm_output_tokens}")
            await safe_update_job_status(job_id, "COMPLETED", result=simplified_result)

            TOKENS_INPUT.labels(consumer=consumer).inc(billable_input_tokens)
            TOKENS_OUTPUT.labels(consumer=consumer).inc(vllm_output_tokens)
            JOBS_COMPLETED.labels(consumer=consumer).inc()
            JOB_DURATION.labels(consumer=consumer).observe(time.time() - start_time)
        else:
            error_msg = f"vLLM HTTP {response.status_code}: {response.text[:500]}"
            logger.error(f"[job={job_id}] {error_msg}")
            await safe_update_job_status(job_id, "FAILED", error=error_msg)
            JOBS_FAILED.labels(consumer=consumer).inc()
    except httpx.TimeoutException:
        error_msg = f"vLLM timeout after {VLLM_TIMEOUT}s"
        logger.error(f"[job={job_id}] {error_msg}")
        await safe_update_job_status(job_id, "FAILED", error=error_msg)
        JOBS_FAILED.labels(consumer=consumer).inc()
    except Exception as e:
        logger.error(f"[job={job_id}] Unexpected error: {e}")
        await safe_update_job_status(job_id, "FAILED", error=str(e))
        JOBS_FAILED.labels(consumer=consumer).inc()


async def main():
    start_http_server(PROM_PORT)
    logger.info(f"Prometheus metrics server started on port {PROM_PORT}")

    logger.info("═══════════════════════════════════════════════════")
    logger.info("  Async Kafka Job Worker Starting...")
    logger.info(f"  Kafka: {KAFKA_BROKERS} | Topic: {KAFKA_TOPIC}")
    logger.info(f"  vLLM:  {VLLM_URL}")
    logger.info(f"  Concurrency Limit: {CONCURRENCY_LIMIT}")
    logger.info("═══════════════════════════════════════════════════")

    await asyncio.to_thread(init_db_pool)

    consumer = None
    max_retries = 30
    for attempt in range(1, max_retries + 1):
        try:
            consumer = AIOKafkaConsumer(
                KAFKA_TOPIC,
                bootstrap_servers=KAFKA_BROKERS,
                group_id=KAFKA_GROUP_ID,
                auto_offset_reset='earliest',
                enable_auto_commit=False
            )
            await consumer.start()
            logger.info(f"Subscribed to topic: {KAFKA_TOPIC}")
            break
        except Exception as e:
            if attempt == max_retries:
                logger.error(f"Kafka consumer failed after {max_retries} attempts: {e}")
                raise
            logger.warning(f"Kafka not ready (attempt {attempt}/{max_retries}): {e} — retrying in 2s...")
            if consumer:
                try:
                    await consumer.stop()
                except Exception:
                    pass
                consumer = None
            await asyncio.sleep(2)

    global db_semaphore
    db_semaphore = asyncio.Semaphore(15)  # Limit DB concurrent operations to prevent pool exhaustion

    shutdown_event = asyncio.Event()

    def signal_handler():
        logger.info("Shutdown signal received, waiting for active tasks...")
        shutdown_event.set()

    loop = asyncio.get_running_loop()
    for sig in (signal.SIGTERM, signal.SIGINT):
        try:
            loop.add_signal_handler(sig, signal_handler)
        except NotImplementedError:
            pass

    async with httpx.AsyncClient() as client:
        try:
            while not shutdown_event.is_set():
                # Poll a batch of messages
                msg_pack = await consumer.getmany(timeout_ms=1000, max_records=CONCURRENCY_LIMIT)
                
                if not msg_pack:
                    continue
                
                tasks = []
                for tp, msgs in msg_pack.items():
                    for msg in msgs:
                        try:
                            data = json.loads(msg.value.decode('utf-8'))
                            job_id = data.get('job_id')
                            payload = data.get('payload')
                            consumer_name = data.get('consumer', 'default')

                            if not job_id or not payload:
                                logger.error(f"Invalid message format, skipping: {data}")
                                continue

                            # Create processing task
                            task = asyncio.create_task(process_job(job_id, payload, client, consumer=consumer_name))
                            tasks.append(task)
                        except Exception as e:
                            logger.error(f"Failed to parse Kafka message: {e}")
                
                if tasks:
                    logger.debug(f"Awaiting {len(tasks)} concurrent tasks...")
                    results = await asyncio.gather(*tasks, return_exceptions=True)
                    
                    has_db_error = False
                    for r in results:
                        if isinstance(r, Exception):
                            logger.error(f"Task raised exception: {r}")
                            has_db_error = True
                            
                    if has_db_error:
                        logger.critical("Batch failed due to DB/critical errors. Aborting to prevent data loss.")
                        shutdown_event.set()
                        break
                    
                    # Safe commit only after the entire batch is completed successfully
                    try:
                        await consumer.commit()
                    except Exception as e:
                        logger.warning(f"Batch offset commit failed (non-fatal): {e}")

        except asyncio.CancelledError:
            logger.info("Main loop cancelled.")
        finally:
            await consumer.stop()
            logger.info("Kafka consumer stopped.")

            if db_pool:
                db_pool.closeall()
                logger.info("DB connection pool closed.")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logger.info("Process stopped by KeyboardInterrupt.")
