import os
import json
import re
import logging
import asyncio
import signal
import threading
from aiokafka import AIOKafkaConsumer, AIOKafkaProducer
import httpx
import psycopg2
from psycopg2.extras import Json
from psycopg2 import pool
from prometheus_client import Counter, Histogram, start_http_server

# ═══════════════════════════════════════════════════════════════════════════
# Logging
# ═══════════════════════════════════════════════════════════════════════════
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# ═══════════════════════════════════════════════════════════════════════════
# Prometheus Metrics
# ═══════════════════════════════════════════════════════════════════════════
PROM_PORT = int(os.environ.get('METRICS_PORT', '9090'))

TOKENS_INPUT = Counter(
    'medgemma_input_tokens_total',
    'Total billable input tokens consumed',
    ['consumer']
)
TOKENS_OUTPUT = Counter(
    'medgemma_output_tokens_total',
    'Total output tokens generated by vLLM',
    ['consumer']
)
JOBS_COMPLETED = Counter(
    'medgemma_jobs_completed_total',
    'Total jobs completed successfully',
    ['consumer']
)
JOBS_FAILED = Counter(
    'medgemma_jobs_failed_total',
    'Total jobs that failed',
    ['consumer']
)
JOB_DURATION = Histogram(
    'medgemma_job_duration_seconds',
    'Job processing duration (vLLM inference time)',
    ['consumer'],
    buckets=[1, 5, 10, 30, 60, 120, 300, 600]
)
JOBS_RETRIED = Counter(
    'medgemma_jobs_retried_total',
    'Total jobs sent back for retry',
    ['consumer']
)
JOBS_DLQ = Counter(
    'medgemma_jobs_dlq_total',
    'Total jobs sent to dead letter queue',
    ['consumer']
)

# ═══════════════════════════════════════════════════════════════════════════
# Environment variables
# ═══════════════════════════════════════════════════════════════════════════
KAFKA_BROKERS = os.environ.get('KAFKA_BROKERS', 'kafka:9092')
KAFKA_TOPIC = os.environ.get('KAFKA_TOPIC', 'llm-jobs')
KAFKA_DLQ_TOPIC = os.environ.get('KAFKA_DLQ_TOPIC', 'llm-jobs-dlq')
KAFKA_GROUP_ID = os.environ.get('KAFKA_GROUP_ID', 'llm-jobs-worker-group')
MAX_RETRIES = int(os.environ.get('MAX_RETRIES', '3'))

PG_HOST = os.environ.get('PG_HOST', 'kong-database')
PG_PORT = os.environ.get('PG_PORT', '5432')
PG_USER = os.environ.get('PG_USER', 'kong')
PG_PASSWORD = os.environ.get('PG_PASSWORD', 'kong')
PG_DATABASE = os.environ.get('PG_DATABASE', 'kong')

VLLM_URL = os.environ.get('VLLM_URL', 'http://213.173.107.138:20804/v1/chat/completions')
CONCURRENCY_LIMIT = int(os.environ.get('CONCURRENCY_LIMIT', '128'))
VLLM_TIMEOUT = int(os.environ.get('VLLM_TIMEOUT', '120'))

# ═══════════════════════════════════════════════════════════════════════════
# vLLM operatör-kontrollü ayarlar — müşteri input'unu override eder (Dokploy env)
# ═══════════════════════════════════════════════════════════════════════════
VLLM_MODEL = os.environ.get('VLLM_MODEL', 'google/medgemma-1.5-4b-it')
VLLM_TEMPERATURE = float(os.environ.get('VLLM_TEMPERATURE', '0.1'))
VLLM_TOP_P = float(os.environ.get('VLLM_TOP_P', '0.95'))
VLLM_TOP_K = int(os.environ.get('VLLM_TOP_K', '40'))
VLLM_MIN_P = float(os.environ.get('VLLM_MIN_P', '0.05'))
VLLM_REPETITION_PENALTY = float(os.environ.get('VLLM_REPETITION_PENALTY', '1.1'))
VLLM_MAX_TOKENS = int(os.environ.get('VLLM_MAX_TOKENS', '2048'))

# Grounding istekleri için ayrı model (default: normal modelle aynı).
# "grounding": true bayraklı job'lar bu modelle çalışır, diğer trafik etkilenmez.
GROUNDING_VLLM_MODEL = os.environ.get('GROUNDING_VLLM_MODEL', VLLM_MODEL)

# ═══════════════════════════════════════════════════════════════════════════
# DB connection pool
# ═══════════════════════════════════════════════════════════════════════════
db_pool = None

def init_db_pool():
    global db_pool
    db_pool = pool.ThreadedConnectionPool(
        minconn=10,
        maxconn=150,
        host=PG_HOST,
        port=PG_PORT,
        user=PG_USER,
        password=PG_PASSWORD,
        database=PG_DATABASE
    )
    logger.info("DB connection pool initialized (min=10, max=150).")


def update_job_status(job_id, status, result=None, error=None):
    conn = None
    try:
        conn = db_pool.getconn()
        cur = conn.cursor()
        if result is not None:
            cur.execute(
                "UPDATE llm_jobs SET status = %s, result = %s, updated_at = NOW() WHERE job_id = %s",
                (status, Json(result), job_id)
            )
        elif error is not None:
            cur.execute(
                "UPDATE llm_jobs SET status = %s, error = %s, updated_at = NOW() WHERE job_id = %s",
                (status, error, job_id)
            )
        else:
            cur.execute(
                "UPDATE llm_jobs SET status = %s, updated_at = NOW() WHERE job_id = %s",
                (status, job_id)
            )
        conn.commit()
        cur.close()
    except Exception as e:
        logger.error(f"Failed to update job {job_id} in DB: {e}")
        if conn:
            conn.rollback()
        raise  # Critical: Raise error so process_job fails and offset is not committed
    finally:
        if conn:
            db_pool.putconn(conn)

db_semaphore = None

async def safe_update_job_status(*args, **kwargs):
    async with db_semaphore:
        await asyncio.to_thread(update_job_status, *args, **kwargs)


def calculate_billable_input_tokens(payload):
    """
    Müşteriye faturalanacak input token sayısını hesaplar.

    Tüm bileşenler aynı BPE tahmini ile hesaplanır:
    Her 4 karakter ≈ 2.5 token (len * 25 // 40)
    """
    messages = payload.get("messages", [])
    total_chars = 0

    for msg in messages:
        content = msg.get("content")

        if isinstance(content, str):
            total_chars += len(content)
            continue

        if isinstance(content, list):
            for part in content:
                if part.get("type") == "text":
                    total_chars += len(part.get("text", ""))
                elif part.get("type") == "image_url":
                    url = part.get("image_url", {}).get("url", "")
                    if url.startswith("data:image/"):
                        try:
                            _, b64_data = url.split(",", 1)
                            total_chars += len(b64_data)
                        except ValueError:
                            pass

    return max(1, total_chars * 25 // 40)


def sanitize_image_payload(payload):
    """
    Kafka JSON serialization sırasında base64 verisinde oluşabilecek
    whitespace/newline/escape sorunlarını temizler.
    vLLM'in data URI'yi image token olarak işlemesini garanti eder.
    """
    messages = payload.get("messages")
    if not messages:
        return payload

    for msg in messages:
        content = msg.get("content")
        if not isinstance(content, list):
            continue
        for part in content:
            if part.get("type") != "image_url":
                continue
            image_url_obj = part.get("image_url", {})
            url = image_url_obj.get("url", "")
            if not url.startswith("data:image/"):
                continue

            try:
                header, b64_data = url.split(",", 1)
            except ValueError:
                continue

            b64_clean = b64_data.replace("\n", "").replace("\r", "").replace(" ", "").replace("\t", "")
            image_url_obj["url"] = f"{header},{b64_clean}"
            logger.info(f"Image sanitized: {len(b64_data)} -> {len(b64_clean)} chars")

    return payload


def extract_grounding_boxes(content):
    """
    Tek-görsel grounding cevabındaki "Final Answer:" sonrası JSON listesini parse eder.
    Beklenen: [{"box_2d": [y_min, x_min, y_max, x_max], "label": "..."}]
    Dönüş: ham item listesi (doğrulama yapılmaz). Bulunamazsa [].
    """
    if not content or "final answer" not in content.casefold():
        return []
    tail = content.lower().rfind("final answer")
    tail_text = content[tail:]
    fence = re.search(r"```json\s*(\[.*?\])\s*```", tail_text, flags=re.DOTALL | re.IGNORECASE)
    raw = fence.group(1) if fence else None
    if raw is None:
        bracket = re.search(r"(\[.*\])", tail_text, flags=re.DOTALL)
        raw = bracket.group(1) if bracket else None
    if raw is None:
        return []
    try:
        items = json.loads(raw)
    except Exception:
        return []
    if not isinstance(items, list):
        return []
    return [x for x in items if isinstance(x, dict)]


def validate_box_2d(box):
    """
    box_2d [y_min, x_min, y_max, x_max] kontrolü.
    Dönüş: (status, reason); status ∈ {"ok", "suspicious", "invalid"}.
    Kutu = AI bölge önerisidir; "suspicious" frontend'de uyarıyla gösterilir.
    """
    if not isinstance(box, (list, tuple)) or len(box) != 4:
        return "invalid", "box_2d must have 4 elements"
    try:
        ymn, xmn, ymx, xmx = [int(v) for v in box]
    except Exception:
        return "invalid", "box_2d must be integers"
    if not (0 <= ymn < ymx <= 1000 and 0 <= xmn < xmx <= 1000):
        return "invalid", f"box out of range: {ymn},{xmn},{ymx},{xmx}"
    area = (ymx - ymn) * (xmx - xmn)
    if area > 200000 and all(v % 50 == 0 for v in (ymn, xmn, ymx, xmx)):
        return "suspicious", (
            f"box too large ({area / 10000:.0f}% of image, round numbers) - "
            "likely hallucinated center-box, requires visual verification"
        )
    return "ok", "ok"


async def handle_failure(job_id, payload, consumer_name, retry_count, error_msg, producer):
    """Retry logic: retry < MAX_RETRIES → requeue, else → DLQ"""
    if retry_count < MAX_RETRIES:
        retry_msg = json.dumps({
            "job_id": job_id,
            "payload": payload,
            "consumer": consumer_name,
            "retry_count": retry_count + 1
        }).encode('utf-8')
        await producer.send_and_wait(KAFKA_TOPIC, retry_msg)
        await safe_update_job_status(job_id, "RETRYING", error=f"[retry {retry_count + 1}/{MAX_RETRIES}] {error_msg}")
        JOBS_RETRIED.labels(consumer=consumer_name).inc()
        logger.warning(f"[job={job_id}] Retrying ({retry_count + 1}/{MAX_RETRIES}): {error_msg}")
    else:
        dlq_msg = json.dumps({
            "job_id": job_id,
            "payload": payload,
            "consumer": consumer_name,
            "retry_count": retry_count,
            "error": error_msg
        }).encode('utf-8')
        await producer.send_and_wait(KAFKA_DLQ_TOPIC, dlq_msg)
        await safe_update_job_status(job_id, "FAILED", error=f"[DLQ after {MAX_RETRIES} retries] {error_msg}")
        JOBS_FAILED.labels(consumer=consumer_name).inc()
        JOBS_DLQ.labels(consumer=consumer_name).inc()
        logger.error(f"[job={job_id}] Moved to DLQ after {MAX_RETRIES} retries: {error_msg}")


async def process_job(job_id, payload, client, producer, consumer="default", retry_count=0):
    logger.info(f"[job={job_id}] Processing (attempt {retry_count + 1})...")
    await safe_update_job_status(job_id, "PROCESSING")

    import time
    start_time = time.time()

    try:
        payload.pop("medasista_metadata", None)

        # Grounding opt-in: {"grounding": true} olan job'lar GROUNDING_VLLM_MODEL
        # ile çalışır. Bayrak vLLM'e gönderilmez ama retry'de korunur (payload'da kalır).
        grounding_requested = bool(payload.get("grounding", False))

        # Faturalanacak input token sayısı
        billable_input_tokens = calculate_billable_input_tokens(payload)

        req_payload = {k: v for k, v in payload.items() if k != "grounding"}
        req_payload = sanitize_image_payload(req_payload)

        # Content sıralaması: text parçaları image'dan önce gelmeli
        # MedGemma text-first sıralamada daha iyi sonuç veriyor
        if isinstance(req_payload.get("messages"), list):
            for msg in req_payload["messages"]:
                content = msg.get("content")
                if isinstance(content, list):
                    text_parts = [p for p in content if p.get("type") == "text"]
                    image_parts = [p for p in content if p.get("type") == "image_url"]
                    other_parts = [p for p in content if p.get("type") not in ("text", "image_url")]
                    msg["content"] = text_parts + image_parts + other_parts

        # Operatör-kontrollü model ve sampling — müşteri input'unu override eder
        req_payload["model"] = GROUNDING_VLLM_MODEL if grounding_requested else VLLM_MODEL
        req_payload["temperature"] = VLLM_TEMPERATURE
        req_payload["top_p"] = VLLM_TOP_P
        req_payload["top_k"] = VLLM_TOP_K
        req_payload["min_p"] = VLLM_MIN_P
        req_payload["repetition_penalty"] = VLLM_REPETITION_PENALTY
        req_payload["max_tokens"] = VLLM_MAX_TOKENS
        req_payload.pop("stream", None)

        user_msg = next((m for m in req_payload.get("messages", []) if m.get("role") == "user"), None)
        content_order = [p.get("type") for p in user_msg["content"]] if user_msg and isinstance(user_msg.get("content"), list) else "N/A"
        logger.info(
            f"[job={job_id}] vLLM payload: model={req_payload['model']}, "
            f"temp={req_payload['temperature']}, top_p={req_payload['top_p']}, "
            f"top_k={req_payload['top_k']}, min_p={req_payload['min_p']}, "
            f"rep_penalty={req_payload['repetition_penalty']}, max_tokens={req_payload['max_tokens']}, "
            f"grounding={grounding_requested}, content_order={content_order}"
        )

        response = await client.post(VLLM_URL, json=req_payload, timeout=float(VLLM_TIMEOUT))

        if response.status_code == 200:
            raw_result = response.json()

            content = ""
            choices = raw_result.get("choices", [])
            if choices and isinstance(choices, list) and choices[0].get("message"):
                content = choices[0]["message"].get("content", "")

            # MedGemma thinking token'larını temizle (<unused94>thought...<unused95>)
            if "<unused94>" in content:
                content = re.sub(r"<unused94>.*?<unused95>", "", content, flags=re.DOTALL).strip()

            logger.info(f"[job={job_id}] raw_content_len={len(content)} raw_preview={content[:500]!r}")

            # Grounding çıktısı: "Final Answer:" JSON listesi → boxes[]
            boxes = []
            for item in extract_grounding_boxes(content):
                status, reason = validate_box_2d(item.get("box_2d"))
                boxes.append({
                    "label": str(item.get("label", "")),
                    "box_2d": item.get("box_2d"),
                    "status": status,
                    "reason": reason,
                })
            if boxes and grounding_requested:
                bad = [b for b in boxes if b["status"] == "invalid"]
                if bad:
                    logger.warning(f"[job={job_id}] grounding invalid boxes: {bad}")

            vllm_output_tokens = raw_result.get("usage", {}).get("completion_tokens", 0)
            total_tokens = billable_input_tokens + vllm_output_tokens

            simplified_result = {
                "content": content,
                "boxes": boxes,
                "usage": {
                    "input_tokens": billable_input_tokens,
                    "output_tokens": vllm_output_tokens,
                    "total_tokens": total_tokens
                }
            }

            logger.info(f"[job={job_id}] Completed. Input(billable): {billable_input_tokens}, Output: {vllm_output_tokens}")
            await safe_update_job_status(job_id, "COMPLETED", result=simplified_result)

            TOKENS_INPUT.labels(consumer=consumer).inc(billable_input_tokens)
            TOKENS_OUTPUT.labels(consumer=consumer).inc(vllm_output_tokens)
            JOBS_COMPLETED.labels(consumer=consumer).inc()
            JOB_DURATION.labels(consumer=consumer).observe(time.time() - start_time)
        else:
            error_msg = f"vLLM HTTP {response.status_code}: {response.text[:500]}"
            await handle_failure(job_id, payload, consumer, retry_count, error_msg, producer)
    except httpx.TimeoutException:
        error_msg = f"vLLM timeout after {VLLM_TIMEOUT}s"
        await handle_failure(job_id, payload, consumer, retry_count, error_msg, producer)
    except Exception as e:
        error_msg = str(e)
        logger.error(f"[job={job_id}] Unexpected error: {error_msg}")
        await handle_failure(job_id, payload, consumer, retry_count, error_msg, producer)


async def main():
    start_http_server(PROM_PORT)
    logger.info(f"Prometheus metrics server started on port {PROM_PORT}")

    logger.info("═══════════════════════════════════════════════════")
    logger.info("  Async Kafka Job Worker Starting...")
    logger.info(f"  Kafka: {KAFKA_BROKERS} | Topic: {KAFKA_TOPIC}")
    logger.info(f"  vLLM:  {VLLM_URL}")
    logger.info(f"  Concurrency Limit: {CONCURRENCY_LIMIT}")
    logger.info("═══════════════════════════════════════════════════")

    await asyncio.to_thread(init_db_pool)

    consumer = None
    max_retries = 30
    for attempt in range(1, max_retries + 1):
        try:
            consumer = AIOKafkaConsumer(
                KAFKA_TOPIC,
                bootstrap_servers=KAFKA_BROKERS,
                group_id=KAFKA_GROUP_ID,
                auto_offset_reset='earliest',
                enable_auto_commit=False
            )
            await consumer.start()
            logger.info(f"Subscribed to topic: {KAFKA_TOPIC}")
            break
        except Exception as e:
            if attempt == max_retries:
                logger.error(f"Kafka consumer failed after {max_retries} attempts: {e}")
                raise
            logger.warning(f"Kafka not ready (attempt {attempt}/{max_retries}): {e} — retrying in 2s...")
            if consumer:
                try:
                    await consumer.stop()
                except Exception:
                    pass
                consumer = None
            await asyncio.sleep(2)

    global db_semaphore
    db_semaphore = asyncio.Semaphore(50)

    shutdown_event = asyncio.Event()

    def signal_handler():
        logger.info("Shutdown signal received, waiting for active tasks...")
        shutdown_event.set()

    loop = asyncio.get_running_loop()
    for sig in (signal.SIGTERM, signal.SIGINT):
        try:
            loop.add_signal_handler(sig, signal_handler)
        except NotImplementedError:
            pass

    producer = AIOKafkaProducer(bootstrap_servers=KAFKA_BROKERS)
    await producer.start()
    logger.info("Kafka producer started (for retry/DLQ)")

    async with httpx.AsyncClient(limits=httpx.Limits(max_connections=150, max_keepalive_connections=100)) as client:
        try:
            while not shutdown_event.is_set():
                # Poll a batch of messages
                msg_pack = await consumer.getmany(timeout_ms=1000, max_records=CONCURRENCY_LIMIT)

                if not msg_pack:
                    continue

                tasks = []
                for tp, msgs in msg_pack.items():
                    for msg in msgs:
                        try:
                            data = json.loads(msg.value.decode('utf-8'))
                            job_id = data.get('job_id')
                            payload = data.get('payload')
                            consumer_name = data.get('consumer', 'default')
                            retry_count = data.get('retry_count', 0)

                            if not job_id or not payload:
                                logger.error(f"Invalid message format, skipping: {data}")
                                continue

                            task = asyncio.create_task(process_job(
                                job_id, payload, client, producer,
                                consumer=consumer_name, retry_count=retry_count
                            ))
                            tasks.append(task)
                        except Exception as e:
                            logger.error(f"Failed to parse Kafka message: {e}")
                
                if tasks:
                    logger.debug(f"Awaiting {len(tasks)} concurrent tasks...")
                    results = await asyncio.gather(*tasks, return_exceptions=True)
                    
                    has_db_error = False
                    for r in results:
                        if isinstance(r, Exception):
                            logger.error(f"Task raised exception: {r}")
                            has_db_error = True
                            
                    if has_db_error:
                        logger.critical("Batch failed due to DB/critical errors. Aborting to prevent data loss.")
                        shutdown_event.set()
                        break
                    
                    # Safe commit only after the entire batch is completed successfully
                    try:
                        await consumer.commit()
                    except Exception as e:
                        logger.warning(f"Batch offset commit failed (non-fatal): {e}")

        except asyncio.CancelledError:
            logger.info("Main loop cancelled.")
        finally:
            await producer.stop()
            logger.info("Kafka producer stopped.")
            await consumer.stop()
            logger.info("Kafka consumer stopped.")

            if db_pool:
                db_pool.closeall()
                logger.info("DB connection pool closed.")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logger.info("Process stopped by KeyboardInterrupt.")
